# Generated by Django 3.2.23 on 2024-01-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20240114_1749'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductSizePrice',
            new_name='ProductSize',
        ),
    ]
