# Generated by Django 3.2.22 on 2023-10-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_min_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='min_price',
            new_name='min_product_size_price',
        ),
    ]
