# Generated by Django 3.2.22 on 2023-10-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_min_price_product_min_product_size_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='min_product_size_price',
        ),
    ]
