# Generated by Django 3.2.22 on 2023-10-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_min_product_size_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
