# Generated by Django 3.2.22 on 2023-10-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_min_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='min_price',
        ),
    ]
